# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 67e0908d68996221d596fed8a9d289a16011f68ada46f51386342f0982c0cad4d094aa09c04de21c51055ff793fe2ccc28472bdab51b54e1b32c3518fe9e8834

test:
  secret_key_base: 9e24d213bdf8d9e199ee3c9babccf24506611d3cc60596ca629e99b4c64b4c087f9725a64c9c89fb2da278e3195488f97d3952d922d38e21c47e65f5d9227c71

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
